// <auto-generated />
using AplikasiKendaraan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AplikasiKendaraan.Migrations
{
    [DbContext(typeof(AplikasiKendaraanContext))]
    [Migration("20220923081648_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AplikasiKendaraan.Model.KendaraanModel", b =>
                {
                    b.Property<string>("no_register")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("alamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bahanBakar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("merk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("silinder")
                        .HasColumnType("int");

                    b.Property<int>("tahun")
                        .HasColumnType("int");

                    b.Property<string>("warna")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("no_register");

                    b.ToTable("KendaraanModel");
                });
#pragma warning restore 612, 618
        }
    }
}
